name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, zip

      - name: Install PHP CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Check PHP syntax
        run: php -l .

      - name: Upload dist folder artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-production
          path: dist
      # เพิ่มขั้นตอนสำหรับการสร้างไฟล์ JSON หรือเรียกใช้ API ตามความต้องการของคุณ

