name: PHP Build and Deploy

on:
  push:
    branches:
      - main  # เลือก branch ที่คุณต้องการที่จะ trigger workflow
  pull_request:
    branches:
      - main  # เลือก branch ที่คุณต้องการที่จะ trigger workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # เลือกเวอร์ชันของ PHP ที่คุณต้องการใช้

      - name: Install dependencies
        run: composer install  # ติดตั้ง dependencies ของคุณ (ถ้ามี)

      - name: Build Docker image
        run: docker build -t your-image-name:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push your-image-name:latest

      - name: Deploy to Docker
        run: |
          docker pull your-image-name:latest
          docker run -d -p 8080:80 your-image-name:latest  # แก้ไขพอร์ตตามที่คุณต้องการ
